# Generated by Django 6.1.1 on 2026-09-15 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_name', models.CharField(default='Wrench', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Professional Service Provider', max_length=255)),
                ('about_me', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('is_price_negotiable', models.BooleanField(default=True)),
                ('experience_years', models.PositiveIntegerField(default=1)),
                ('education', models.CharField(blank=True, default='ITI / Diploma', max_length=255)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(default='Rajahmundry', max_length=100)),
                ('state', models.CharField(default='Andhra Pradesh', max_length=100)),
                ('service_radius_km', models.FloatField(default=10.0)),
                ('latitude', models.FloatField(default=17.0005)),
                ('longitude', models.FloatField(default=81.804)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline')], default='AVAILABLE', max_length=20)),
                ('available_days', models.JSONField(blank=True, default=list)),
                ('working_hours', models.CharField(default='10:00 AM - 6:00 PM', max_length=100)),
                ('rating', models.FloatField(default=4.5)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('elo_rating', models.FloatField(default=1500.0)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='workers.workercategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('start_year', models.CharField(max_length=20)),
                ('end_year', models.CharField(default='Present', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='workers.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='worker_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='workers.workerprofile')),
            ],
        ),
    ]
