# Generated by Django 6.1.1 on 2026-10-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_booking_accepted_at_booking_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='billing_cycle',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, help_text='Subscription end date', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_pattern',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='billing_cycle',
            field=models.CharField(choices=[('PER_VISIT', 'Per Visit / Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly Lump-sum')], default='PER_VISIT', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for recurring schedule/subscription', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('ONE_TIME', 'One-time Task'), ('RECURRING', 'Recurring / Subscription')], default='ONE_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='recurrence_pattern',
            field=models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily (7 Days/Week)'), ('WEEKDAYS', 'Weekdays (Mon-Fri)'), ('ALTERNATE_DAYS', 'Alternate Days'), ('WEEKLY', 'Weekly (1 Day/Week)'), ('MONTHLY', 'Monthly Contract')], default='NONE', max_length=20),
        ),
    ]
